"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aktest_se.types import BaseModel
from aktest_se.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteEnrollmentRequestTypedDict(TypedDict):
    enrollment_id: int
    r"""Enrollment on which to perform the desired operation."""
    allow_cancel_pending_changes: NotRequired[bool]
    r"""Cancels all pending changes when updating an enrollment."""
    deploy_not_after: NotRequired[str]
    r"""Don't deploy after this date (UTC)."""
    deploy_not_before: NotRequired[str]
    r"""Don't deploy before this date (UTC)."""
    account_switch_key: NotRequired[str]
    r"""For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys)."""


class DeleteEnrollmentRequest(BaseModel):
    enrollment_id: Annotated[
        int,
        pydantic.Field(alias="enrollmentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Enrollment on which to perform the desired operation."""

    allow_cancel_pending_changes: Annotated[
        Optional[bool],
        pydantic.Field(alias="allow-cancel-pending-changes"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Cancels all pending changes when updating an enrollment."""

    deploy_not_after: Annotated[
        Optional[str],
        pydantic.Field(alias="deploy-not-after"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Don't deploy after this date (UTC)."""

    deploy_not_before: Annotated[
        Optional[str],
        pydantic.Field(alias="deploy-not-before"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Don't deploy before this date (UTC)."""

    account_switch_key: Annotated[
        Optional[str],
        pydantic.Field(alias="accountSwitchKey"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""For customers who manage more than one account, this [runs the operation from another account](https://techdocs.akamai.com/developer/docs/manage-many-accounts-with-one-api-client). The Identity and Access Management API provides a [list of available account switch keys](https://techdocs.akamai.com/iam-api/reference/get-client-account-switch-keys)."""


class DeleteEnrollmentEnrollmentsResponseBodyTypedDict(TypedDict):
    r"""Encapsulates information for enrollment status."""

    changes: List[str]
    r"""Identifies the modification taken on the enrollment."""
    enrollment: str
    r"""Identifies the enrollment modified."""


class DeleteEnrollmentEnrollmentsResponseBody(BaseModel):
    r"""Encapsulates information for enrollment status."""

    changes: List[str]
    r"""Identifies the modification taken on the enrollment."""

    enrollment: str
    r"""Identifies the enrollment modified."""


class DeleteEnrollmentResponseBodyTypedDict(TypedDict):
    r"""Encapsulates information for enrollment status."""

    changes: List[str]
    r"""Identifies the modification taken on the enrollment."""
    enrollment: str
    r"""Identifies the enrollment modified."""


class DeleteEnrollmentResponseBody(BaseModel):
    r"""Encapsulates information for enrollment status."""

    changes: List[str]
    r"""Identifies the modification taken on the enrollment."""

    enrollment: str
    r"""Identifies the enrollment modified."""


DeleteEnrollmentResponseTypedDict = Union[
    DeleteEnrollmentResponseBodyTypedDict,
    DeleteEnrollmentEnrollmentsResponseBodyTypedDict,
]


DeleteEnrollmentResponse = Union[
    DeleteEnrollmentResponseBody, DeleteEnrollmentEnrollmentsResponseBody
]
